# Generated by Django 5.2.12 on 2026-03-04 21:06

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(help_text='Tenant slug used for subdomain resolution. Example: acme -> acme.app.com', max_length=63, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.RegexValidator(message='Slug must be lowercase alphanumeric and hyphens, 1-63 chars, cannot start/end with hyphen.', regex='^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$')])),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='organizatio_slug_048085_idx'), models.Index(fields=['status'], name='organizatio_status_295901_idx'), models.Index(fields=['created_at'], name='organizatio_created_dfd536_idx')],
                'constraints': [models.UniqueConstraint(fields=('slug',), name='uniq_organization_slug')],
            },
        ),
    ]
