# Generated by Django 5.2.12 on 2026-03-05 00:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_membership'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='rbac_capabi_code_29ceca_idx'), models.Index(fields=['is_active'], name='rbac_capabi_is_acti_343c20_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Org-scoped stable code (used by imports).', max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organization_id', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MembershipRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_roles', to='accounts.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_roles', to='rbac.role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoleCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_capabilities', to='rbac.capability')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_capabilities', to='rbac.role')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MembershipCapabilityGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_grants', to='rbac.capability')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_grants', to='accounts.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['organization', 'created_at'], name='rbac_member_organiz_a62545_idx'), models.Index(fields=['organization', 'updated_at'], name='rbac_member_organiz_6a04f4_idx'), models.Index(fields=['organization', 'membership'], name='rbac_member_organiz_161c3b_idx'), models.Index(fields=['organization', 'capability'], name='rbac_member_organiz_c8e64c_idx'), models.Index(fields=['organization', 'allowed'], name='rbac_member_organiz_8e8c20_idx')],
                'constraints': [models.UniqueConstraint(fields=('membership', 'capability'), name='uniq_membership_capability_grant')],
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['organization', 'created_at'], name='rbac_role_organiz_25b2ab_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['organization', 'updated_at'], name='rbac_role_organiz_0e0287_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['organization', 'is_active'], name='rbac_role_organiz_195702_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['organization', 'code'], name='rbac_role_organiz_91f6f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_role_org_code'),
        ),
        migrations.AddIndex(
            model_name='membershiprole',
            index=models.Index(fields=['organization', 'created_at'], name='rbac_member_organiz_95f9a9_idx'),
        ),
        migrations.AddIndex(
            model_name='membershiprole',
            index=models.Index(fields=['organization', 'updated_at'], name='rbac_member_organiz_1837b6_idx'),
        ),
        migrations.AddIndex(
            model_name='membershiprole',
            index=models.Index(fields=['organization', 'membership'], name='rbac_member_organiz_78d9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='membershiprole',
            index=models.Index(fields=['organization', 'role'], name='rbac_member_organiz_1dfc90_idx'),
        ),
        migrations.AddConstraint(
            model_name='membershiprole',
            constraint=models.UniqueConstraint(fields=('membership', 'role'), name='uniq_membership_role'),
        ),
        migrations.AddIndex(
            model_name='rolecapability',
            index=models.Index(fields=['organization', 'created_at'], name='rbac_roleca_organiz_bd1a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='rolecapability',
            index=models.Index(fields=['organization', 'updated_at'], name='rbac_roleca_organiz_a6a345_idx'),
        ),
        migrations.AddIndex(
            model_name='rolecapability',
            index=models.Index(fields=['organization', 'role'], name='rbac_roleca_organiz_50ca5b_idx'),
        ),
        migrations.AddIndex(
            model_name='rolecapability',
            index=models.Index(fields=['organization', 'capability'], name='rbac_roleca_organiz_8cef0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='rolecapability',
            constraint=models.UniqueConstraint(fields=('role', 'capability'), name='uniq_role_capability'),
        ),
    ]
